name: Publish Docker Image

# on:
#   release:
#     types: [published]

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  push_to_registries:

    name: Push Docker image to multiple registries

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:

      - 
        name: Check out the repo
        uses: actions/checkout@v3

      - 
        name: Get Version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo Version: $VERSION

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - 
      #   name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      #   with:
      #     images: |
      #       my-docker-hub-namespace/my-docker-hub-repository
      #       ghcr.io/${{ github.repository }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: block-foundation/algorand-indexer:${{ env.VERSION }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: block-foundation/algorand-indexer:latest
